ACCEPT_PROPOSAL = 'accept-proposal'  # The action of accepting a previously submitted propose to perform an action.
AGREE = 'agree'  # The action of agreeing to perform a requestd action made by another agent. Agent will carry it out.
CANCEL = 'cancel'  # Agent wants to cancel a previous request.
CFP = 'cfp'  # Agent issues a call for proposals. It contains the actions to be carried out and any other terms of the agreement.
CONFIRM = 'confirm'  # The sender confirms to the receiver the truth of the content. The sender initially believed that the receiver was unsure about it.
DISCONFIRM = 'disconfirm'  # The sender confirms to the receiver the falsity of the content.
FAILURE = 'failure'  # Tell the other agent that a previously requested action failed.
INFORM = 'inform'  # Tell another agent something. The sender must believe in the truth of the statement. Most used performative.
INFORM_IF = 'inform-if'  # Used as content of request to ask another agent to tell us is a statement is true or false.
INFORM_REF = 'inform-ref'  # Like inform-if but asks for the value of the expression.
NOT_UNDERSTOOD = 'not-understood'  # Sent when the agent did not understand the message.
PROPAGATE = 'propagate'  # Asks another agent so forward this same propagate message to others.
PROPOSE = 'propose'  # Used as a response to a cfp. Agent proposes a deal.
PROXY = 'proxy'  # The sender wants the receiver to select target agents denoted by a given description and to send an embedded message to them.
QUERY_IF = 'query-if'  # The action of asking another agent whether or not a given proposition is true.
QUERY_REF = 'query-ref'  # The action of asking another agent for the object referred to by an referential expression.
REFUSE = 'refuse'  # The action of refusing to perform a given action, and explaining the reason for the refusal.
REJECT_PROPOSAL = 'reject-proposal'  # The action of rejecting a proposal to perform some action during a negotiation.
REQUEST = 'request'  # The sender requests the receiver to perform some action. Usually to request the receiver to perform another communicative act.
REQUEST_WHEN = 'request-when'  # The sender wants the receiver to perform some action when some given proposition becomes true.
REQUEST_WHENEVER = 'request-whenever'  # The sender wants the receiver to perform some action as soon as some proposition becomes true and thereafter each time the proposition becomes true again.
SUBSCRIBE = 'subscribe' # The act of requesting a persistent intention to notify the sender of the value of a reference, and to notify again whenever the object identified by the reference changes.